-- ============================================================================
-- APEX Storage API - Tables and REST Handlers
-- For storing Endpoints and Instances centrally
-- ============================================================================
--
-- Instructions:
-- 1. Run this script in your Oracle APEX workspace schema
-- 2. Register REST module in APEX SQL Workshop > RESTful Services
-- 3. Configure the API URL in FusionClient ERP Settings > Page 3: API Storage
--
-- ============================================================================

-- ============================================================================
-- SECTION 1: CREATE TABLES
-- ============================================================================

-- -----------------------------------------------------------------------------
-- Table: FC_ENDPOINTS
-- Stores endpoint configurations for APEX and Fusion integrations
-- -----------------------------------------------------------------------------
CREATE TABLE fc_endpoints (
    endpoint_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sno                 NUMBER,
    source              VARCHAR2(50),           -- APEX or FUSION
    integration_code    VARCHAR2(100) NOT NULL, -- LOGIN, WMS, GL, AR, AP, INV, OM, etc.
    instance_name       VARCHAR2(50),           -- PROD, TEST, DEV
    base_url            VARCHAR2(500),          -- Base URL for the endpoint
    endpoint_path       VARCHAR2(500),          -- Path/endpoint suffix
    comments            VARCHAR2(1000),
    client_id           VARCHAR2(100),          -- Optional: to support multi-tenant
    created_by          VARCHAR2(100) DEFAULT USER,
    created_date        TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_by          VARCHAR2(100),
    updated_date        TIMESTAMP,
    CONSTRAINT fc_endpoints_uk UNIQUE (source, integration_code, instance_name, client_id)
);

-- Add comments
COMMENT ON TABLE fc_endpoints IS 'Stores endpoint configurations for APEX and Fusion integrations';
COMMENT ON COLUMN fc_endpoints.endpoint_id IS 'Primary key';
COMMENT ON COLUMN fc_endpoints.sno IS 'Serial number for ordering';
COMMENT ON COLUMN fc_endpoints.source IS 'Source system: APEX or FUSION';
COMMENT ON COLUMN fc_endpoints.integration_code IS 'Integration code: LOGIN, WMS, GL, AR, AP, INV, OM, etc.';
COMMENT ON COLUMN fc_endpoints.instance_name IS 'Instance name: PROD, TEST, DEV';
COMMENT ON COLUMN fc_endpoints.base_url IS 'Base URL for the endpoint';
COMMENT ON COLUMN fc_endpoints.endpoint_path IS 'Path/endpoint suffix';
COMMENT ON COLUMN fc_endpoints.comments IS 'Additional comments';
COMMENT ON COLUMN fc_endpoints.client_id IS 'Client identifier for multi-tenant support';

-- Create index for faster lookups
CREATE INDEX fc_endpoints_lookup_idx ON fc_endpoints (source, integration_code, instance_name);
CREATE INDEX fc_endpoints_client_idx ON fc_endpoints (client_id);

-- -----------------------------------------------------------------------------
-- Table: FC_INSTANCES
-- Stores instance configurations
-- -----------------------------------------------------------------------------
CREATE TABLE fc_instances (
    instance_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_code       VARCHAR2(50) NOT NULL,  -- PROD, TEST, DEV, UAT, etc.
    instance_name       VARCHAR2(200),          -- Display name
    description         VARCHAR2(500),
    fusion_base_url     VARCHAR2(500),          -- Fusion Cloud base URL
    apex_base_url       VARCHAR2(500),          -- APEX base URL
    is_active           VARCHAR2(1) DEFAULT 'Y',
    is_default          VARCHAR2(1) DEFAULT 'N',
    client_id           VARCHAR2(100),          -- Optional: to support multi-tenant
    sort_order          NUMBER DEFAULT 0,
    created_by          VARCHAR2(100) DEFAULT USER,
    created_date        TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_by          VARCHAR2(100),
    updated_date        TIMESTAMP,
    CONSTRAINT fc_instances_uk UNIQUE (instance_code, client_id)
);

-- Add comments
COMMENT ON TABLE fc_instances IS 'Stores instance configurations';
COMMENT ON COLUMN fc_instances.instance_id IS 'Primary key';
COMMENT ON COLUMN fc_instances.instance_code IS 'Instance code: PROD, TEST, DEV, UAT';
COMMENT ON COLUMN fc_instances.instance_name IS 'Display name for the instance';
COMMENT ON COLUMN fc_instances.fusion_base_url IS 'Oracle Fusion Cloud base URL';
COMMENT ON COLUMN fc_instances.apex_base_url IS 'APEX base URL';
COMMENT ON COLUMN fc_instances.is_active IS 'Is instance active? Y/N';
COMMENT ON COLUMN fc_instances.is_default IS 'Is this the default instance? Y/N';
COMMENT ON COLUMN fc_instances.client_id IS 'Client identifier for multi-tenant support';

-- Create index
CREATE INDEX fc_instances_client_idx ON fc_instances (client_id);
CREATE INDEX fc_instances_active_idx ON fc_instances (is_active);


-- ============================================================================
-- SECTION 2: CREATE REST MODULE AND HANDLERS
-- ============================================================================

-- -----------------------------------------------------------------------------
-- REST Module: fusionclient
-- Base path: /fusionclient/
-- -----------------------------------------------------------------------------
BEGIN
    ORDS.DEFINE_MODULE(
        p_module_name    => 'fusionclient',
        p_base_path      => '/fusionclient/',
        p_items_per_page => 1000,
        p_status         => 'PUBLISHED',
        p_comments       => 'FusionClient ERP API Storage endpoints'
    );
END;
/

-- ============================================================================
-- SECTION 3: ENDPOINTS REST HANDLERS
-- ============================================================================

-- -----------------------------------------------------------------------------
-- Template: endpoints
-- Handles: GET (list all), POST (create new)
-- -----------------------------------------------------------------------------
BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'fusionclient',
        p_pattern        => 'endpoints',
        p_comments       => 'Endpoint configurations'
    );
END;
/

-- GET /endpoints - List all endpoints
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'fusionclient',
        p_pattern        => 'endpoints',
        p_method         => 'GET',
        p_source_type    => 'json/collection',
        p_source         => q'[
            SELECT
                endpoint_id,
                sno,
                source,
                integration_code,
                instance_name,
                base_url,
                endpoint_path,
                comments,
                client_id,
                TO_CHAR(created_date, 'YYYY-MM-DD"T"HH24:MI:SS') as created_date,
                TO_CHAR(updated_date, 'YYYY-MM-DD"T"HH24:MI:SS') as updated_date
            FROM fc_endpoints
            WHERE (:client_id IS NULL OR client_id = :client_id)
            ORDER BY sno, integration_code, instance_name
        ]',
        p_comments       => 'Get all endpoints'
    );

    -- Bind parameter for client filtering
    ORDS.DEFINE_PARAMETER(
        p_module_name        => 'fusionclient',
        p_pattern            => 'endpoints',
        p_method             => 'GET',
        p_name               => 'client_id',
        p_bind_variable_name => 'client_id',
        p_source_type        => 'HEADER',
        p_param_type         => 'STRING',
        p_access_method      => 'IN'
    );
END;
/

-- POST /endpoints - Create new endpoint
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'fusionclient',
        p_pattern        => 'endpoints',
        p_method         => 'POST',
        p_source_type    => 'plsql/block',
        p_source         => q'[
        DECLARE
            l_endpoint_id NUMBER;
        BEGIN
            INSERT INTO fc_endpoints (
                sno,
                source,
                integration_code,
                instance_name,
                base_url,
                endpoint_path,
                comments,
                client_id,
                created_by
            ) VALUES (
                :sno,
                :source,
                :integration_code,
                :instance_name,
                :base_url,
                :endpoint_path,
                :comments,
                :client_id,
                NVL(:created_by, USER)
            )
            RETURNING endpoint_id INTO l_endpoint_id;

            :status_code := 201;
            :endpoint_id := l_endpoint_id;

            HTP.P('{"success": true, "endpoint_id": ' || l_endpoint_id || ', "message": "Endpoint created successfully"}');
        EXCEPTION
            WHEN DUP_VAL_ON_INDEX THEN
                :status_code := 409;
                HTP.P('{"success": false, "message": "Endpoint with this source, integration_code, and instance_name already exists"}');
            WHEN OTHERS THEN
                :status_code := 500;
                HTP.P('{"success": false, "message": "' || REPLACE(SQLERRM, '"', '\"') || '"}');
        END;
        ]',
        p_comments       => 'Create new endpoint'
    );
END;
/

-- -----------------------------------------------------------------------------
-- Template: endpoints/:id
-- Handles: GET (single), PUT (update), DELETE
-- -----------------------------------------------------------------------------
BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'fusionclient',
        p_pattern        => 'endpoints/:id',
        p_comments       => 'Single endpoint operations'
    );
END;
/

-- GET /endpoints/:id - Get single endpoint
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'fusionclient',
        p_pattern        => 'endpoints/:id',
        p_method         => 'GET',
        p_source_type    => 'json/item',
        p_source         => q'[
            SELECT
                endpoint_id,
                sno,
                source,
                integration_code,
                instance_name,
                base_url,
                endpoint_path,
                comments,
                client_id,
                TO_CHAR(created_date, 'YYYY-MM-DD"T"HH24:MI:SS') as created_date,
                TO_CHAR(updated_date, 'YYYY-MM-DD"T"HH24:MI:SS') as updated_date
            FROM fc_endpoints
            WHERE endpoint_id = :id
        ]',
        p_comments       => 'Get single endpoint by ID'
    );
END;
/

-- PUT /endpoints/:id - Update endpoint
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'fusionclient',
        p_pattern        => 'endpoints/:id',
        p_method         => 'PUT',
        p_source_type    => 'plsql/block',
        p_source         => q'[
        DECLARE
            l_count NUMBER;
        BEGIN
            UPDATE fc_endpoints
            SET sno = NVL(:sno, sno),
                source = NVL(:source, source),
                integration_code = NVL(:integration_code, integration_code),
                instance_name = NVL(:instance_name, instance_name),
                base_url = NVL(:base_url, base_url),
                endpoint_path = NVL(:endpoint_path, endpoint_path),
                comments = NVL(:comments, comments),
                updated_by = NVL(:updated_by, USER),
                updated_date = SYSTIMESTAMP
            WHERE endpoint_id = :id;

            l_count := SQL%ROWCOUNT;

            IF l_count > 0 THEN
                :status_code := 200;
                HTP.P('{"success": true, "message": "Endpoint updated successfully", "rows_affected": ' || l_count || '}');
            ELSE
                :status_code := 404;
                HTP.P('{"success": false, "message": "Endpoint not found"}');
            END IF;
        EXCEPTION
            WHEN DUP_VAL_ON_INDEX THEN
                :status_code := 409;
                HTP.P('{"success": false, "message": "Duplicate endpoint configuration"}');
            WHEN OTHERS THEN
                :status_code := 500;
                HTP.P('{"success": false, "message": "' || REPLACE(SQLERRM, '"', '\"') || '"}');
        END;
        ]',
        p_comments       => 'Update endpoint'
    );
END;
/

-- PATCH /endpoints/:id - Partial update endpoint
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'fusionclient',
        p_pattern        => 'endpoints/:id',
        p_method         => 'PATCH',
        p_source_type    => 'plsql/block',
        p_source         => q'[
        DECLARE
            l_count NUMBER;
        BEGIN
            UPDATE fc_endpoints
            SET sno = COALESCE(:sno, sno),
                source = COALESCE(:source, source),
                integration_code = COALESCE(:integration_code, integration_code),
                instance_name = COALESCE(:instance_name, instance_name),
                base_url = COALESCE(:base_url, base_url),
                endpoint_path = COALESCE(:endpoint_path, endpoint_path),
                comments = COALESCE(:comments, comments),
                updated_by = NVL(:updated_by, USER),
                updated_date = SYSTIMESTAMP
            WHERE endpoint_id = :id;

            l_count := SQL%ROWCOUNT;

            IF l_count > 0 THEN
                :status_code := 200;
                HTP.P('{"success": true, "message": "Endpoint updated successfully"}');
            ELSE
                :status_code := 404;
                HTP.P('{"success": false, "message": "Endpoint not found"}');
            END IF;
        EXCEPTION
            WHEN OTHERS THEN
                :status_code := 500;
                HTP.P('{"success": false, "message": "' || REPLACE(SQLERRM, '"', '\"') || '"}');
        END;
        ]',
        p_comments       => 'Partial update endpoint'
    );
END;
/

-- DELETE /endpoints/:id - Delete endpoint
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'fusionclient',
        p_pattern        => 'endpoints/:id',
        p_method         => 'DELETE',
        p_source_type    => 'plsql/block',
        p_source         => q'[
        DECLARE
            l_count NUMBER;
        BEGIN
            DELETE FROM fc_endpoints
            WHERE endpoint_id = :id;

            l_count := SQL%ROWCOUNT;

            IF l_count > 0 THEN
                :status_code := 200;
                HTP.P('{"success": true, "message": "Endpoint deleted successfully"}');
            ELSE
                :status_code := 404;
                HTP.P('{"success": false, "message": "Endpoint not found"}');
            END IF;
        EXCEPTION
            WHEN OTHERS THEN
                :status_code := 500;
                HTP.P('{"success": false, "message": "' || REPLACE(SQLERRM, '"', '\"') || '"}');
        END;
        ]',
        p_comments       => 'Delete endpoint'
    );
END;
/

-- -----------------------------------------------------------------------------
-- Template: endpoints/bulk
-- Handles: POST (bulk upsert)
-- -----------------------------------------------------------------------------
BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'fusionclient',
        p_pattern        => 'endpoints/bulk',
        p_comments       => 'Bulk endpoint operations'
    );
END;
/

-- POST /endpoints/bulk - Bulk upsert endpoints
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'fusionclient',
        p_pattern        => 'endpoints/bulk',
        p_method         => 'POST',
        p_source_type    => 'plsql/block',
        p_source         => q'[
        DECLARE
            l_json      CLOB := :body_text;
            l_count     NUMBER := 0;
            l_inserted  NUMBER := 0;
            l_updated   NUMBER := 0;
        BEGIN
            -- Parse JSON array and upsert each endpoint
            FOR rec IN (
                SELECT jt.*
                FROM JSON_TABLE(l_json, '$[*]'
                    COLUMNS (
                        sno              NUMBER        PATH '$.sno',
                        source           VARCHAR2(50)  PATH '$.source',
                        integration_code VARCHAR2(100) PATH '$.integration_code',
                        instance_name    VARCHAR2(50)  PATH '$.instance_name',
                        base_url         VARCHAR2(500) PATH '$.base_url',
                        endpoint_path    VARCHAR2(500) PATH '$.endpoint_path',
                        comments         VARCHAR2(1000) PATH '$.comments',
                        client_id        VARCHAR2(100) PATH '$.client_id'
                    )
                ) jt
            )
            LOOP
                BEGIN
                    MERGE INTO fc_endpoints t
                    USING (
                        SELECT rec.source AS source,
                               rec.integration_code AS integration_code,
                               rec.instance_name AS instance_name,
                               rec.client_id AS client_id
                        FROM dual
                    ) s
                    ON (t.source = s.source
                        AND t.integration_code = s.integration_code
                        AND t.instance_name = s.instance_name
                        AND NVL(t.client_id, 'NULL') = NVL(s.client_id, 'NULL'))
                    WHEN MATCHED THEN
                        UPDATE SET
                            t.sno = rec.sno,
                            t.base_url = rec.base_url,
                            t.endpoint_path = rec.endpoint_path,
                            t.comments = rec.comments,
                            t.updated_by = USER,
                            t.updated_date = SYSTIMESTAMP
                    WHEN NOT MATCHED THEN
                        INSERT (sno, source, integration_code, instance_name, base_url, endpoint_path, comments, client_id)
                        VALUES (rec.sno, rec.source, rec.integration_code, rec.instance_name, rec.base_url, rec.endpoint_path, rec.comments, rec.client_id);

                    IF SQL%ROWCOUNT > 0 THEN
                        l_count := l_count + 1;
                    END IF;
                EXCEPTION
                    WHEN OTHERS THEN
                        NULL; -- Skip individual errors, continue processing
                END;
            END LOOP;

            COMMIT;

            :status_code := 200;
            HTP.P('{"success": true, "message": "Bulk operation completed", "processed": ' || l_count || '}');
        EXCEPTION
            WHEN OTHERS THEN
                ROLLBACK;
                :status_code := 500;
                HTP.P('{"success": false, "message": "' || REPLACE(SQLERRM, '"', '\"') || '"}');
        END;
        ]',
        p_comments       => 'Bulk upsert endpoints'
    );
END;
/


-- ============================================================================
-- SECTION 4: INSTANCES REST HANDLERS
-- ============================================================================

-- -----------------------------------------------------------------------------
-- Template: instances
-- Handles: GET (list all), POST (create new)
-- -----------------------------------------------------------------------------
BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'fusionclient',
        p_pattern        => 'instances',
        p_comments       => 'Instance configurations'
    );
END;
/

-- GET /instances - List all instances
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'fusionclient',
        p_pattern        => 'instances',
        p_method         => 'GET',
        p_source_type    => 'json/collection',
        p_source         => q'[
            SELECT
                instance_id,
                instance_code,
                instance_name,
                description,
                fusion_base_url,
                apex_base_url,
                is_active,
                is_default,
                client_id,
                sort_order,
                TO_CHAR(created_date, 'YYYY-MM-DD"T"HH24:MI:SS') as created_date,
                TO_CHAR(updated_date, 'YYYY-MM-DD"T"HH24:MI:SS') as updated_date
            FROM fc_instances
            WHERE (:client_id IS NULL OR client_id = :client_id)
              AND (:active_only IS NULL OR is_active = 'Y')
            ORDER BY sort_order, instance_code
        ]',
        p_comments       => 'Get all instances'
    );

    -- Bind parameters
    ORDS.DEFINE_PARAMETER(
        p_module_name        => 'fusionclient',
        p_pattern            => 'instances',
        p_method             => 'GET',
        p_name               => 'client_id',
        p_bind_variable_name => 'client_id',
        p_source_type        => 'HEADER',
        p_param_type         => 'STRING',
        p_access_method      => 'IN'
    );

    ORDS.DEFINE_PARAMETER(
        p_module_name        => 'fusionclient',
        p_pattern            => 'instances',
        p_method             => 'GET',
        p_name               => 'active_only',
        p_bind_variable_name => 'active_only',
        p_source_type        => 'URI',
        p_param_type         => 'STRING',
        p_access_method      => 'IN'
    );
END;
/

-- POST /instances - Create new instance
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'fusionclient',
        p_pattern        => 'instances',
        p_method         => 'POST',
        p_source_type    => 'plsql/block',
        p_source         => q'[
        DECLARE
            l_instance_id NUMBER;
        BEGIN
            -- If setting as default, clear other defaults first
            IF :is_default = 'Y' THEN
                UPDATE fc_instances
                SET is_default = 'N',
                    updated_by = USER,
                    updated_date = SYSTIMESTAMP
                WHERE client_id = :client_id OR (:client_id IS NULL AND client_id IS NULL);
            END IF;

            INSERT INTO fc_instances (
                instance_code,
                instance_name,
                description,
                fusion_base_url,
                apex_base_url,
                is_active,
                is_default,
                client_id,
                sort_order,
                created_by
            ) VALUES (
                :instance_code,
                :instance_name,
                :description,
                :fusion_base_url,
                :apex_base_url,
                NVL(:is_active, 'Y'),
                NVL(:is_default, 'N'),
                :client_id,
                NVL(:sort_order, 0),
                NVL(:created_by, USER)
            )
            RETURNING instance_id INTO l_instance_id;

            :status_code := 201;
            :instance_id := l_instance_id;

            HTP.P('{"success": true, "instance_id": ' || l_instance_id || ', "message": "Instance created successfully"}');
        EXCEPTION
            WHEN DUP_VAL_ON_INDEX THEN
                :status_code := 409;
                HTP.P('{"success": false, "message": "Instance with this code already exists"}');
            WHEN OTHERS THEN
                :status_code := 500;
                HTP.P('{"success": false, "message": "' || REPLACE(SQLERRM, '"', '\"') || '"}');
        END;
        ]',
        p_comments       => 'Create new instance'
    );
END;
/

-- -----------------------------------------------------------------------------
-- Template: instances/:id
-- Handles: GET (single), PUT (update), DELETE
-- -----------------------------------------------------------------------------
BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'fusionclient',
        p_pattern        => 'instances/:id',
        p_comments       => 'Single instance operations'
    );
END;
/

-- GET /instances/:id - Get single instance
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'fusionclient',
        p_pattern        => 'instances/:id',
        p_method         => 'GET',
        p_source_type    => 'json/item',
        p_source         => q'[
            SELECT
                instance_id,
                instance_code,
                instance_name,
                description,
                fusion_base_url,
                apex_base_url,
                is_active,
                is_default,
                client_id,
                sort_order,
                TO_CHAR(created_date, 'YYYY-MM-DD"T"HH24:MI:SS') as created_date,
                TO_CHAR(updated_date, 'YYYY-MM-DD"T"HH24:MI:SS') as updated_date
            FROM fc_instances
            WHERE instance_id = :id
        ]',
        p_comments       => 'Get single instance by ID'
    );
END;
/

-- PUT /instances/:id - Update instance
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'fusionclient',
        p_pattern        => 'instances/:id',
        p_method         => 'PUT',
        p_source_type    => 'plsql/block',
        p_source         => q'[
        DECLARE
            l_count NUMBER;
            l_client_id VARCHAR2(100);
        BEGIN
            -- Get current client_id for the instance
            SELECT client_id INTO l_client_id
            FROM fc_instances
            WHERE instance_id = :id;

            -- If setting as default, clear other defaults first
            IF :is_default = 'Y' THEN
                UPDATE fc_instances
                SET is_default = 'N',
                    updated_by = USER,
                    updated_date = SYSTIMESTAMP
                WHERE instance_id != :id
                  AND (client_id = l_client_id OR (l_client_id IS NULL AND client_id IS NULL));
            END IF;

            UPDATE fc_instances
            SET instance_code = NVL(:instance_code, instance_code),
                instance_name = NVL(:instance_name, instance_name),
                description = NVL(:description, description),
                fusion_base_url = NVL(:fusion_base_url, fusion_base_url),
                apex_base_url = NVL(:apex_base_url, apex_base_url),
                is_active = NVL(:is_active, is_active),
                is_default = NVL(:is_default, is_default),
                sort_order = NVL(:sort_order, sort_order),
                updated_by = NVL(:updated_by, USER),
                updated_date = SYSTIMESTAMP
            WHERE instance_id = :id;

            l_count := SQL%ROWCOUNT;

            IF l_count > 0 THEN
                :status_code := 200;
                HTP.P('{"success": true, "message": "Instance updated successfully"}');
            ELSE
                :status_code := 404;
                HTP.P('{"success": false, "message": "Instance not found"}');
            END IF;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                :status_code := 404;
                HTP.P('{"success": false, "message": "Instance not found"}');
            WHEN DUP_VAL_ON_INDEX THEN
                :status_code := 409;
                HTP.P('{"success": false, "message": "Duplicate instance code"}');
            WHEN OTHERS THEN
                :status_code := 500;
                HTP.P('{"success": false, "message": "' || REPLACE(SQLERRM, '"', '\"') || '"}');
        END;
        ]',
        p_comments       => 'Update instance'
    );
END;
/

-- PATCH /instances/:id - Partial update instance
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'fusionclient',
        p_pattern        => 'instances/:id',
        p_method         => 'PATCH',
        p_source_type    => 'plsql/block',
        p_source         => q'[
        DECLARE
            l_count NUMBER;
        BEGIN
            UPDATE fc_instances
            SET instance_code = COALESCE(:instance_code, instance_code),
                instance_name = COALESCE(:instance_name, instance_name),
                description = COALESCE(:description, description),
                fusion_base_url = COALESCE(:fusion_base_url, fusion_base_url),
                apex_base_url = COALESCE(:apex_base_url, apex_base_url),
                is_active = COALESCE(:is_active, is_active),
                is_default = COALESCE(:is_default, is_default),
                sort_order = COALESCE(:sort_order, sort_order),
                updated_by = NVL(:updated_by, USER),
                updated_date = SYSTIMESTAMP
            WHERE instance_id = :id;

            l_count := SQL%ROWCOUNT;

            IF l_count > 0 THEN
                :status_code := 200;
                HTP.P('{"success": true, "message": "Instance updated successfully"}');
            ELSE
                :status_code := 404;
                HTP.P('{"success": false, "message": "Instance not found"}');
            END IF;
        EXCEPTION
            WHEN OTHERS THEN
                :status_code := 500;
                HTP.P('{"success": false, "message": "' || REPLACE(SQLERRM, '"', '\"') || '"}');
        END;
        ]',
        p_comments       => 'Partial update instance'
    );
END;
/

-- DELETE /instances/:id - Delete instance
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'fusionclient',
        p_pattern        => 'instances/:id',
        p_method         => 'DELETE',
        p_source_type    => 'plsql/block',
        p_source         => q'[
        DECLARE
            l_count NUMBER;
        BEGIN
            DELETE FROM fc_instances
            WHERE instance_id = :id;

            l_count := SQL%ROWCOUNT;

            IF l_count > 0 THEN
                :status_code := 200;
                HTP.P('{"success": true, "message": "Instance deleted successfully"}');
            ELSE
                :status_code := 404;
                HTP.P('{"success": false, "message": "Instance not found"}');
            END IF;
        EXCEPTION
            WHEN OTHERS THEN
                :status_code := 500;
                HTP.P('{"success": false, "message": "' || REPLACE(SQLERRM, '"', '\"') || '"}');
        END;
        ]',
        p_comments       => 'Delete instance'
    );
END;
/

-- -----------------------------------------------------------------------------
-- Template: instances/default
-- Handles: GET (get default instance)
-- -----------------------------------------------------------------------------
BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'fusionclient',
        p_pattern        => 'instances/default',
        p_comments       => 'Default instance'
    );
END;
/

-- GET /instances/default - Get default instance
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'fusionclient',
        p_pattern        => 'instances/default',
        p_method         => 'GET',
        p_source_type    => 'json/item',
        p_source         => q'[
            SELECT
                instance_id,
                instance_code,
                instance_name,
                description,
                fusion_base_url,
                apex_base_url,
                is_active,
                is_default,
                client_id,
                sort_order
            FROM fc_instances
            WHERE is_default = 'Y'
              AND is_active = 'Y'
              AND (:client_id IS NULL OR client_id = :client_id)
            FETCH FIRST 1 ROW ONLY
        ]',
        p_comments       => 'Get default instance'
    );

    ORDS.DEFINE_PARAMETER(
        p_module_name        => 'fusionclient',
        p_pattern            => 'instances/default',
        p_method             => 'GET',
        p_name               => 'client_id',
        p_bind_variable_name => 'client_id',
        p_source_type        => 'HEADER',
        p_param_type         => 'STRING',
        p_access_method      => 'IN'
    );
END;
/


-- ============================================================================
-- SECTION 5: SEED DATA (Optional)
-- ============================================================================

-- Uncomment and modify to insert initial data
/*
-- Insert default instances
INSERT INTO fc_instances (instance_code, instance_name, description, is_active, is_default, sort_order)
VALUES ('PROD', 'Production', 'Production Environment', 'Y', 'Y', 1);

INSERT INTO fc_instances (instance_code, instance_name, description, is_active, is_default, sort_order)
VALUES ('TEST', 'Test', 'Test Environment', 'Y', 'N', 2);

INSERT INTO fc_instances (instance_code, instance_name, description, is_active, is_default, sort_order)
VALUES ('DEV', 'Development', 'Development Environment', 'Y', 'N', 3);

COMMIT;
*/


-- ============================================================================
-- SECTION 6: GRANT PERMISSIONS (if needed)
-- ============================================================================

-- If using APEX Authentication, grant access to REST module
-- ORDS.CREATE_ROLE('fusionclient_role');
-- ORDS.CREATE_PRIVILEGE('fusionclient_priv', 'FusionClient API Access', 'fusionclient_role');
-- ORDS.CREATE_PRIVILEGE_MAPPING('fusionclient_priv', 'fusionclient/*');


-- ============================================================================
-- SECTION 7: API DOCUMENTATION
-- ============================================================================
/*

API Endpoints Summary:
======================

ENDPOINTS API:
--------------
GET    /fusionclient/endpoints              - List all endpoints
POST   /fusionclient/endpoints              - Create new endpoint
GET    /fusionclient/endpoints/:id          - Get single endpoint
PUT    /fusionclient/endpoints/:id          - Update endpoint (full)
PATCH  /fusionclient/endpoints/:id          - Update endpoint (partial)
DELETE /fusionclient/endpoints/:id          - Delete endpoint
POST   /fusionclient/endpoints/bulk         - Bulk upsert endpoints

INSTANCES API:
--------------
GET    /fusionclient/instances              - List all instances
POST   /fusionclient/instances              - Create new instance
GET    /fusionclient/instances/:id          - Get single instance
PUT    /fusionclient/instances/:id          - Update instance (full)
PATCH  /fusionclient/instances/:id          - Update instance (partial)
DELETE /fusionclient/instances/:id          - Delete instance
GET    /fusionclient/instances/default      - Get default instance

Query Parameters:
-----------------
GET /endpoints?client_id=xxx               - Filter by client
GET /instances?active_only=Y               - Only active instances

Headers:
--------
client_id: <client_identifier>             - For multi-tenant filtering
Authorization: Basic <base64_credentials>  - If authentication enabled

Request/Response Format:
------------------------
Content-Type: application/json

Sample Endpoint JSON:
{
    "sno": 1,
    "source": "APEX",
    "integration_code": "LOGIN",
    "instance_name": "PROD",
    "base_url": "https://apex.oracle.com/pls/apex",
    "endpoint_path": "/login",
    "comments": "Login endpoint",
    "client_id": "CLIENT001"
}

Sample Instance JSON:
{
    "instance_code": "PROD",
    "instance_name": "Production",
    "description": "Production Environment",
    "fusion_base_url": "https://xxx.fa.us2.oraclecloud.com",
    "apex_base_url": "https://apex.oracle.com/pls/apex",
    "is_active": "Y",
    "is_default": "Y",
    "sort_order": 1,
    "client_id": "CLIENT001"
}

Bulk Upsert Example:
[
    {"sno": 1, "source": "APEX", "integration_code": "LOGIN", "instance_name": "PROD", "base_url": "...", "endpoint_path": "..."},
    {"sno": 2, "source": "APEX", "integration_code": "WMS", "instance_name": "PROD", "base_url": "...", "endpoint_path": "..."}
]

*/

COMMIT;
